### ISSUE TITLE
Create Set of Golden Data for the Input PDFs

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#3]

**Comment by lukehsiao** [comment]
Just a thought for the future, we may be able to utilize Mechanical Turk (or something similar) just to get us a nice set of golden data. It wouldn't cost too much and it is something we can consider in the future.

**Comment by xiao-cheng** [comment]
Yes, I once got AMT to annotate the binary relations for the entire freebase for only ~$2k in 3 days.

**Comment by lukehsiao** [comment]
@xiao-cheng, would it be correct to say that it would be better to have holes in the data, than to have potentially incorrect data? For example, some datasheets may not label a particular specification clearly, or may not list a particular spec. Would it be better for skip entries I feel are questionable? 

I assume it would be more useful to be able to trust the data, even if there is less of it, right?

**Comment by xiao-cheng** [comment]
@lukehsiao It is actually the opposite. Always include the data because the worst thing that can happen is that we assign zero probability to it in the inference stage, which is equivalent to leave them out. If you leave out any data before the inference, there is no way to recover your early mistakes. This is typical in a pipeline system and the whole point of using DeepDive is to do joint inference to prevent error propagation.

**Comment by lukehsiao** [comment]
Ah, I see. Well, I'll make sure that all cells have my best guesses then, at least. Thanks!

**Comment by xiao-cheng** [comment]
That being said, if you can do something simple at >99% accuracy, I'm all for simpler and more scalable architectures.

**Comment by lukehsiao** [comment]
So, I've pulled all the data I could from the source pdfs. There are several PDFs where a particular value isn't listed. I will show you what the data looks like. We may want to just eliminate the columns where there is some uncertainty for simplicity, but we can decide after you see what we have.
