### ISSUE TITLE
Restructuring code to prepare for adding other relations (multinomial classification)

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#40]
To Do:
- [x] Restructure gold data to be of the form `(doc_id, part_num, text, mtype)`

**Comment by xiao-cheng** [comment]
The multiclass branch now supports negative downsampling, the default is to have equal number of positive and negative examples. This is done by associating each mention with a random probability for being sampled, then at runtime we simply threshold this number to decide whether to assign negative label during supervision. 

The result is over 0.9 for minimum confidence in true positives and about 0.01% false positive rate using the same threshold. Some confusion is had in these false positives, but mostly because we do not have stg_temp_max in the system right now.

**Comment by xiao-cheng** [comment]
The hack by using a random number column can be eliminated after https://github.com/HazyResearch/ddlog/issues/89 is fixed

**Comment by lukehsiao** [comment]
Awesome! I will have the new gold data up tomorrow so we can try expanding. It sounds like trying storage temp max next would be good to confirm your hypothesis.

**Comment by lukehsiao** [comment]
@xiao-cheng: Here is the transformed gold data file:

[transformed_gold_data.zip](https://github.com/lukehsiao/HardwareDeepDive/files/212325/transformed_gold_data.zip)

I've also added the script used to generate it to the `multiclass` branch.

**Comment by xiao-cheng** [comment]
We now use a new approach to restrict the the scope of a matching part-attr pair. Document-wide matches are of scope -1 while specific alignments gives a document-level unique postive integer scope id

**Comment by xiao-cheng** [comment]
Done
