### ISSUE TITLE
Do we want table-extraction in this repo?

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#68]
Hey @hchiang, I noticed you pushed table-extraction straight to the master branch. Are we sure we want it in this repo? Let's try to put stuff in `master` through the branching and pull requesting in rather than committing directly so master has a cleaner history.

I'm going to remove the `.DS_STORE` OSX files you committed, for now. 

Is there a particular reason you wanted to hard separate from xiao's repo?

**Comment by hchiang** [comment]
I wanted to reference some of the code you have in the master branch, so I added table-extraction to the master branch. I figured it'd also be a way to start merging the two branches since almost all the stuff I've been working on in the key-extractor branch has been in the table-extraction directory.
